### PR TITLE
Remove all CLI only APIs

### PR DESCRIPTION
**Pull request by tao1991123**
Some apis only work in cli mode and they could not be pass into webpack-dev-server config.

@see 
- https://webpack.js.org/configuration/dev-server/#devserver-color-cli-only
- https://webpack.js.org/configuration/dev-server/#devserver-info-cli-only
- https://webpack.js.org/configuration/dev-server/#devserver-progress-cli-only
- https://webpack.js.org/configuration/dev-server/#devserver-stdin-cli-only

Related Issue: #120

### CODE REVIEW

**Comment by eliperelman** [comment]
Note that this is a breaking change.

**Comment by tao1991123** [comment]
> Note that this is a breaking change.

I think it's not a break change, just a bugfix.

In Node API mode, Webpack-dev-server will validate the option [schema](https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json) 

these apis usage will result in Invalidate Error. so nobody is using these apis.

Now the removal of these apis will not affect any program.

**Comment by eliperelman** [comment]
@tao1991123 the chain API is independent of its integration with webpack-dev-server, so the removal of any method would be a breaking change for the API regardless of where it is integrated. Also, the API tries to maintain compatibility back to webpack 2, so the removal of a method could have potential breaking changes.

**Comment by tao1991123** [comment]
ok, I get it.
so what should i do now?
modify the package.json MINOR version or close this pr or something else

**Comment by edmorley** [comment]
Why was this closed? :-)

This seems like a good change to make (we just need to ensure the first release that includes it bumps the major version).

**Comment by yordis** [comment]
@edmorley any updates on this one?

**Comment by eliperelman** [comment]
I still don't think we should do this. Just because certain configuration by webpack is only used by the API and not the CLI doesn't mean these the CLI methods cannot be consumed by our API and still used for the webpack CLI:

```js
const Config = require('webpack-chain');

const config = new Config();

config.devServer
  .color(false)
  .info(false)
  .progress(true)
  .stdin(true);

spawn('webpack', stringify(config.toConfig()));
// webpack --color false --info false --progress --stdin
```

**Comment by yordis** [comment]
@eliperelman that is a good point! Definitely didn't think about this.

I would reject this proposal based on your observation.

**Comment by edmorley** [comment]
Closing for the reasons mentioned here:
https://github.com/neutrinojs/webpack-chain/pull/127#issuecomment-507365827

**Pull request closed without merging**
