### PR TITLE
Create index.d.ts

### PR DESCRIPTION
**Pull request by Jetsly**
#62 
Copy from 
```
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-chain/index.d.ts
```

add 
```
mode(value: 'development' | 'production') : this;
parallelism(value: number) : this;
```
modify
```
minimizer(value: webpack.Plugin[]): this;
=>
minimizer(name: string): Config.Plugin<this>;
```

### CODE REVIEW

**Comment by Jetsly** [comment]
if write with typescript can auto extract the `.d.ts` file

**Comment by eliperelman** [comment]
We won't be using TypeScript for the code itself.

**Comment by edmorley** [comment]
Why was this closed? :-)

We'll happily accept definitions so long as tested on Travis (either as a separate definitions file, or as in-line comments if that form is supported by TypeScript, similar to flow's feature?).

**Comment by Jetsly** [comment]
i modify  incomplete

**Pull request closed without merging**
