### PR TITLE
Adding devServer shorthands for sockHost, sockPort, sockPath. Resolves #231

### LINKED ISSUE #231: Support devServer.sockHost, devServer.sockPath, and devServer.sockPort
Thanks for your work on this project - I enjoy  using it.

I would love to see [devServer.sockHost](https://webpack.js.org/configuration/dev-server/#devserversockhost), [devServer.sockPort](https://webpack.js.org/configuration/dev-server/#devserversockport), and [devServer.sockPath](https://webpack.js.org/configuration/dev-server/#devserversockpath) supported in webpack chain. As far as I can tell, they currently are not supported at all.

### PR DESCRIPTION
**Pull request by joeldenning**
Note that setting sockHost, sockPort, and sockPath were already possible via `config.devServer.set('sockPort', '8080')`. However, this adds shorthand methods for them.

Resolves #231

### CODE REVIEW

**Comment by joeldenning** [comment]
👍 I will add types later. Regarding tests. I actually wrote some tests earlier but removed them because it seemed like testing this.extends() wasn’t being done for other properties on devServer. Am happy to reinstate those tests though.

**Comment by edmorley** [comment]
Yeah I agree tests for the items in `this.extends()` is likely unnecessary. By types tests I meant `types/test/webpack-chain-tests.ts` (sorry for not being clearer!).

**Comment by joeldenning** [comment]
👍 Updated with your feedback. Github diff seems to be getting confused after I merged master into this branch and it's showing stuff that's on the master branch as new to this PR (devtoolNamespace). But that's not new to this PR

**Comment by edmorley** [comment]
> Github diff seems to be getting confused after I merged master into this branch and it's showing stuff that's on the master branch as new to this PR (devtoolNamespace)

Yeah that was strange - I've toggled the base branch and that seems to have fixed the GitHub diff :-)

**Comment by edmorley** [comment]
Released in v6.4.0.

**Pull request merged**
