### PR TITLE
Add `devtoolNamespace` TypeScript declaration

### PR DESCRIPTION
**Pull request by sirlancelot**
Match implementation from https://github.com/neutrinojs/webpack-chain/blob/59dfdaf/src/Output.js

### CODE REVIEW

**Comment by edmorley** [comment]
Also could you add a usage of `devtoolNamespace` to `types/test/webpack-chain-tests.ts` so that it's tested?

**Comment by sirlancelot** [comment]
will do!

**Comment by sirlancelot** [comment]
Updated & Rebased on to current `master`

**Comment by edmorley** [comment]
Released in v6.4.0.

**Pull request merged**
