### PR TITLE
support webpack 5.x

### PR DESCRIPTION
**Pull request by githoniel**
this PR will make `webpack-chain` work with webpack5 #266 

I have checked the [documentation](https://webpack.js.org/configuration/) for all supported options.

- Class: use `CreateClass(superClass)` to support chained class inherited
- Configuration: support almost all options in webpack5 and remove undocumented options. 
    - partial support `Module Contexts` options. since they are document as deprecated and will soon be removed, so only parameters that the demo is provided in the documentation are supported
    - add new type `ChainedValueMap` to support object/boolean type for `node/performance` option as #252 suggested, API like `config.node(false)`.
    - add tests for new config
- Type declaration: use the type definition that comes with `webpack` itself
- CI: change to use Github Actions
- Doc: readme has updated

### CODE REVIEW

**Comment by githoniel** [comment]
@edmorley I have no idea how to deal with Travis CI, any idea?

**Comment by githoniel** [comment]
I have finished CI migration and update type definition. Github actions did not trigger on this PR but it work well in my fork. I think it will work after merge. 

I will work on doc update soon

**Comment by githoniel** [comment]
I have finished CI migration, update type definition and readme. 

Github actions did not trigger on this PR but it work well in my fork. I think it will work after merge. 

@edmorley

**Comment by githoniel** [comment]
I have finished CI migration, update type definition and readme.

Github actions did not trigger on this PR but it work well in my fork. I think it will work after merge.

@edmorley

**Review by edmorley — COMMENTED** [review]
Than you for the PR!

Could you split out the Travis CI to GitHub Actions migration to its own PR, so I can review/merge that separately/first? :-)

**Comment by edmorley** [comment]
Btw I've just renamed the `master` branch to `main`. GitHub gives these instructions for updating local repos:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by githoniel** [comment]
@edmorley I have create https://github.com/neutrinojs/webpack-chain/pull/304

**Comment by githoniel** [comment]
conflict resolved and all test pass now

**Comment by githoniel** [comment]
@edmorley do you have time to review this? 

my fork version [@gem-mine/webpack-chain](https://www.npmjs.com/package/@gem-mine/webpack-chain) of this pr  has been used in our private cli and work well

**Comment by wonderfulMan** [comment]
> @edmorley do you have time to review this?
> 
> my fork version [@gem-mine/webpack-chain](https://www.npmjs.com/package/@gem-mine/webpack-chain) of this pr has been used in our private cli and work well

I finally found that it supports version 5.0, you helped my work 
Good luck！

**Comment by JaxXu** [comment]
There are still some problems with the `splitChunks` type support .
```
        config
            .optimization
                .splitChunks({
                    name: false,
                    chunks: 'all',
                }) // WebStorm prompts to return Optimization
                .end() // WebStorm prompts to return Config;
```
In fact, you need one more `end` to return Config

**Comment by githoniel** [comment]
@JaxXu  thanks for testing. I have fixed it

**Comment by JaxXu** [comment]
> @JaxXu thanks for testing. I have fixed it

Great, now it works very well in my project . Thank you for your work!

**Comment by 0x1af2aec8f957** [comment]
@githoniel 
Can webpack-dev-server be upgraded to V4 together？
I noticed this remark:
https://github.com/githoniel/webpack-chain/blob/bdbdb85c4338200ef9fbd8108d5709431a6f8cae/types/index.d.ts#L245-L246

The complete migration plan is here:
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by githoniel** [comment]
> @githoniel
> Can `webpack-dev-server` be upgraded to v4 together？
> I noticed this remark:
> https://github.com/githoniel/webpack-chain/blob/bdbdb85c4338200ef9fbd8108d5709431a6f8cae/types/index.d.ts#L245-L246
> 
> The complete migration plan is here:
> https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

thank you for remind me, it will fix this soon

**Comment by 0x1af2aec8f957** [comment]
@githoniel I see the update. Thank you for your work.

**Comment by 0x1af2aec8f957** [comment]
@githoniel 
I found a new problem：

webpack-chain config:

```typescript

config
    .mode(ENV)
    .cache(true)
    .name(packageInfo.name)
    .stats({
        assets: false,
        modules: false,
        runtimeModules: false,
        cachedModules: false,
        assetsSort: '!size'
    })
    .devtool(isDevelopment ? 'eval-source-map' : false) /// doc: https://webpack.js.org/configuration/devtool/#devtool
    .entry('main')
      .add(path.resolve(workDir, 'src', 'main.ts'))
    .end()
    .output
      .clean(true)
      .path(path.resolve(workDir, projectName))
      .filename(isDevelopment ? 'js/[name].js' : 'js/[name].[chunkhash:8].js')
      .assetModuleFilenamet(isDevelopment ? 'asset/[name].[ext]' : 'asset/[name].[contenthash:8].[ext][query]') /// doc: https://webpack.js.org/configuration/output/#outputassetmodulefilename
      .publicPath(publicPath)
    .end();
```

webpack-chain error:
```bash
[webpack-cli] Failed to load '/tmp/webpack.base.ts' config
[webpack-cli] TypeError: config.mode(...).cache(...).name(...).stats(...).devtool(...).entry(...).add(...).end(...).output.clean(...).path(...).filename(...).assetModuleFilenamet is not a function
```

I noticed the definition of types in the code: 
Type definition：https://github.com/githoniel/webpack-chain/blob/9b1f73cead509ca63fd65b70016107bea4202ffa/types/index.d.ts#L207
Actual code：https://github.com/githoniel/webpack-chain/blob/9b1f73cead509ca63fd65b70016107bea4202ffa/src/Output.js#L20

Why not use `assetmodulefilename` for the type definition here? Is it due to a writing error?

**Comment by githoniel** [comment]
> ```shell
> assetModuleFilenamet
> ```

It should be `assetModuleFilename` not `assetModuleFilenamet` ?

**Comment by githoniel** [comment]
@0x1af2aec8f957 
It should be `assetModuleFilename` not `assetModuleFilenamet` ?

**Comment by 0x1af2aec8f957** [comment]
> @0x1af2aec8f957
> It should be `assetModuleFilename` not `assetModuleFilenamet` ?

yes

**Comment by edmorley** [comment]
Hi! Thank you for your work on this, and sorry for the delay in taking a look at it.

The PR is pretty large at the moment (+2,717 −3,358) and contains several different types of changes, which makes it harder to review.

Would it be possible to split as many changes out of the PR as possible that aren't directly related to webpack 5? For example these should be separate PRs:
* Dropping support for Node 10
* Adding a new ChainedValueMap concept (not sure I follow why this is needed? The PR description in a new PR would help me understand this)
* Refactoring webpack-chain base classes (such as the new src/createClass/ additions)
* The sorting some of the existing properties/keys or sections README sections alphabetically

**Review by edmorley — CHANGES_REQUESTED** [review]
Hi! Thank you for your work on this, and sorry for the delay in taking a look at it.

The PR is pretty large at the moment (+2,717 −3,358) and contains several different types of changes, which makes it harder to review.

Would it be possible to split as many changes out of the PR as possible that aren't directly related to webpack 5? For example these should be separate PRs:
* Dropping support for Node 10
* Adding a new ChainedValueMap concept (not sure I follow why this is needed? The PR description in a new PR would help me understand this)
* Refactoring webpack-chain base classes (such as the new `src/createClass/*` additions)
* The sorting some of the existing properties/keys or sections README sections alphabetically

Many thanks :-)

**Comment by 0x1af2aec8f957** [comment]
@githoniel 
A new type inference problem was found：https://github.com/webpack-contrib/terser-webpack-plugin/issues/443#issuecomment-915086408

**Comment by githoniel** [comment]
> Hi! Thank you for your work on this, and sorry for the delay in taking a look at it.
> 
> The PR is pretty large at the moment (+2,717 −3,358) and contains several different types of changes, which makes it harder to review.
> 
> Would it be possible to split as many changes out of the PR as possible that aren't directly related to webpack 5? For example these should be separate PRs:
> 
> * Dropping support for Node 10
> * Adding a new ChainedValueMap concept (not sure I follow why this is needed? The PR description in a new PR would help me understand this)
> * Refactoring webpack-chain base classes (such as the new `src/createClass/*` additions)
> * The sorting some of the existing properties/keys or sections README sections alphabetically
> 
> Many thanks :-)

I will split this later

**Comment by edmorley** [comment]
> Would it be possible to split as many changes out of the PR as possible that aren't directly related to webpack 5? For example these should be separate PRs:
> 
>     * Dropping support for Node 10

I've now done this in #318. I've also bumped the version on `main` to v7, since `main` now contains breaking changes.

Please could new PRs be created for these:

>     * Adding a new ChainedValueMap concept (not sure I follow why this is needed? The PR description in a new PR would help me understand this)
>     * Refactoring webpack-chain base classes (such as the new `src/createClass/*` additions)
>     * The sorting some of the existing properties/keys or sections README sections alphabetically

And just to emphasises - I don't have the time to work on this project myself (I'm not using webpack or doing much front-end any more), so people other than me will need to drive this work. Thank you for everyone's help so far! :-)

**Comment by denghongcai** [comment]
any progress here?

**Comment by Nic128** [comment]
This PR has been published under https://www.npmjs.com/package/@gem-mine/webpack-chain `before` the requests here for change. I have been using that fork publish for my own private webpack 5 neutrino fork. I have not had much issues, at least for my usage.

The work involved here is to split the many changes into consumable bits. Makes for better changelogs and better reviews. As far as I know, no one has started the asked split.

**Comment by nexa-li** [comment]
Hi, how long does it take to upgrade?

**Comment by suanmei** [comment]
image
Thanks for your work firstly. 
There is a question about the Type Definition when I use config.devtool('eval-cheap-module-source-map').

Webpack5's sourceMap named-style is `^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$`

**Comment by lindelleric** [comment]
Thanks for your work! Is there any ambition to finish this PR?

**Comment by AdvancedCat** [comment]
Hi, it's already year 2023 and I can't wait to use this new feature in webpack5. So, how is the progress going with that?

**Comment by imaegoo** [comment]
> Hi, it's already year 2023 and I can't wait to use this new feature in webpack5. So, how is the progress going with that?

@AdvancedCat An easy way is: `yarn remove webpack-chain && yarn add -D @gem-mine/webpack-chain`

**Comment by edmorley** [comment]
Closing since this project is no longer maintained:
https://github.com/neutrinojs/webpack-chain/issues/358

**Pull request closed without merging**
