### PR TITLE
Migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by githoniel**
CI migration to github action

@edmorley

### CODE REVIEW

**Review by edmorley — CHANGES_REQUESTED** [review]
Sorry for the delay reviewing + thank you for the PR! 

This looks good - just some small tweaks:
- could you add back matrix testing on multiple Node versions? From a quick search it seems https://github.com/actions/setup-node is the way to do this. I think the matrix perhaps only needs to run for the `test` job, since all the others are either development workflow related or won't be affected by the version of Node. For Node version, please run against 10, 12, 14 and 16 (whilst 10 is EOL, we should drop support in a separate PR).
- for the `on` event definition, it seems the current config could be simplified to `on: [push, pull_request]` - unless I'm misunderstanding how that works? :-)

**Comment by githoniel** [comment]
- `test` job now run  run against 10, 12, 14 and 16 
- `on: [push, pull_request]` is OK ,  shoud we allow pr to any branch?  current config  only allows to run actions when PR to the main branch

**Review by edmorley — COMMENTED** [review]
Sorry for the delay here - work has been very busy.

> `on: [push, pull_request]` is OK , shoud we allow pr to any branch? current config only allows to run actions when PR to the main branch

Yeah I think we want to run actions when PRing other branches too (eg release branches), and at the very least it's not a problem if it does run, so not worth the extra config complexity to prevent it running.

With that change (switching to `on: [push, pull_request]`) this should be good to merge - thank you!

**Review by edmorley — APPROVED** [review]
Many thanks!

**Comment by edmorley** [comment]
@githoniel This worked great :-) 
https://github.com/neutrinojs/webpack-chain/actions/runs/1000308679

**Pull request merged**
